disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "去圖書館借一本書"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

  [params.author]
  name = "Liam Feng"
  email = "zxc6981189@gmail.com"
  headline = "圖書館是你知識的寶庫"

    [[params.author.links]]
    email = "zxc6981189@gmail.com"

["params.author"]
image = "run.png"
